extends RefCounted
class_name GameCapabilityIds

# ======= CONSTS =========
const OBJECT_IDENTITY: StringName = &"object.identity"
const TAGS_QUERY: StringName = &"tags.query"
const TAGS_MODIFY: StringName = &"tags.modify"
const ATTRIBUTES_PROVIDER: StringName = &"attributes.provider"
const ATTRIBUTES_QUERY: StringName = &"attributes.query"
const ATTRIBUTES_MODIFY: StringName = &"attributes.modify"
const METERS_PROVIDER: StringName = &"meters.provider"
const METERS_QUERY: StringName = &"meters.query"
const METERS_MODIFY: StringName = &"meters.modify"
const EFFECTS_RECEIVER: StringName = &"effects.receiver"
const EFFECTS_QUERY: StringName = &"effects.query"
const EFFECTS_DISPEL: StringName = &"effects.dispel"
const EFFECTS_SCHEDULER_HOST: StringName = &"effects.scheduler_host"
const ABILITIES_OWNER: StringName = &"abilities.owner"
const ABILITIES_QUERY: StringName = &"abilities.query"
const ABILITIES_ACTIVATE: StringName = &"abilities.activate"
const ABILITIES_GRANT: StringName = &"abilities.grant"
const ABILITIES_CANCEL: StringName = &"abilities.cancel"
const CONTROL_ARBITER: StringName = &"control.arbiter"
const CONTROL_ENDPOINT: StringName = &"control.endpoint"
const CONTROL_INTENT_RECEIVER: StringName = &"control.intent_receiver"
const CONTROL_QUERY: StringName = &"control.query"
const MOVEMENT_MOTOR: StringName = &"movement.motor"
const MOVEMENT_QUERY: StringName = &"movement.query"
const INTERACTION_SOURCE: StringName = &"interaction.source"
const INTERACTION_TARGET: StringName = &"interaction.target"
const INTERACTION_QUERY: StringName = &"interaction.query"
const INTERACTION_RESERVABLE: StringName = &"interaction.reservable"
const PRESENTATION_CUE_RECEIVER: StringName = &"presentation.cue_receiver"
const OBJECT_RESOLVER: StringName = &"world.object_resolver"
const SPAWN_SERVICE: StringName = &"world.spawn_service"
const TARGETING_SERVICE: StringName = &"world.targeting_service"
const TIME_SERVICE: StringName = &"world.time_service"
const PERSISTENCE_COORDINATOR: StringName = &"world.persistence_coordinator"
const DAMAGE_RECEIVER: StringName = &"damage.receiver"
const DEATH_POLICY: StringName = &"death.policy"
const INVENTORY_OWNER: StringName = &"inventory.owner"
const TEST_COUNTER: StringName = &"test.counter"
const TEST_CHAIN: StringName = &"test.chain"
const TEST_MULTI: StringName = &"test.multi"
const ALL: Array[StringName] = [OBJECT_IDENTITY, TAGS_QUERY, TAGS_MODIFY, ATTRIBUTES_PROVIDER, ATTRIBUTES_QUERY, ATTRIBUTES_MODIFY, METERS_PROVIDER, METERS_QUERY, METERS_MODIFY, EFFECTS_RECEIVER, EFFECTS_QUERY, EFFECTS_DISPEL, EFFECTS_SCHEDULER_HOST, ABILITIES_OWNER, ABILITIES_QUERY, ABILITIES_ACTIVATE, ABILITIES_GRANT, ABILITIES_CANCEL, CONTROL_ARBITER, CONTROL_ENDPOINT, CONTROL_INTENT_RECEIVER, CONTROL_QUERY, MOVEMENT_MOTOR, MOVEMENT_QUERY, INTERACTION_SOURCE, INTERACTION_TARGET, INTERACTION_QUERY, INTERACTION_RESERVABLE, PRESENTATION_CUE_RECEIVER, OBJECT_RESOLVER, SPAWN_SERVICE, TARGETING_SERVICE, TIME_SERVICE, PERSISTENCE_COORDINATOR, DAMAGE_RECEIVER, DEATH_POLICY, INVENTORY_OWNER, TEST_COUNTER, TEST_CHAIN, TEST_MULTI]
static func is_known(capability_id: StringName) -> bool: return capability_id in ALL
